services:
  wis2downloader:
    image: fmidev/wis2downloader
    container_name: wis2downloader
    restart: always
    volumes:
      - /smartmet/data/incoming/wis2/synop:/downloads
    command: >
      -server ssl://globalbroker.meteo.fr:8883
      -topic cache/a/wis2/+/data/core/weather/surface-based-observations/synop
      -username everyone
      -password everyone
      -download /downloads

