services:
  wis2downloader:
    image: wis2downloader
    container_name: wis2downloader
    volumes:
      - /smartmet/data/incoming/wis2:/downloads
    environment:
      - MQTT_SERVER=ssl://globalbroker.meteo.fr:8883
      - MQTT_TOPIC=origin/a/wis2/+/data/core/weather/surface-based-observations/synop
      - MQTT_USERNAME=everyone
      - MQTT_PASSWORD=everyone
    command: >
      sh -c "echo ${MQTT_SERVER} && echo ${MQTT_TOPIC} && echo ${MQTT_USERNAME} && echo ${MQTT_PASSWORD}"

