services:
  smartmetserver:
    image: fmidev/smartmetserver:latest
    container_name: smartmetserver
    labels:
      - "traefik.http.routers.smartmetserver.entrypoints=websecure"
      - "traefik.http.routers.smartmetserver.rule=Host(`data.apps.meteorwanda.gov.rw`)"
      - "traefik.http.services.smartmetserver.loadbalancer.server.port=8080"
    volumes:
      - /smartmet/data/gfs/eastafrica/surface/querydata:/smartmet/data/gfs/surface
      - /smartmet/data/gfs/eastafrica/pressure/querydata:/smartmet/data/gfs/pressure
      - /smartmet/data/ecmwf/world/surface/querydata:/smartmet/data/ecmwf/surface
      - /smartmet/data/wrf/small/surface/querydata:/smartmet/data/wrf/surface
      - /smartmet/data/meteor/rwanda/surface/querydata:/smartmet/data/meteor/surface
      - /smartmet/share/wms:/smartmet/share/wms
      - smartmetserver-storage-cnf:/etc/smartmet
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "2"
    networks:
      - traefik-network
    restart: unless-stopped

volumes:
  smartmetserver-storage-cnf:
    
networks:
    traefik-network:
      external: true
