services:
  smartmetserver:
    image: fmidev/smartmetserver:latest
    container_name: smartmetserver
    labels:
      - "traefik.http.routers.smartmetserver.entrypoints=websecure"
      - "traefik.http.routers.smartmetserver.rule=Host(`data.apps.meteorwanda.gov.rw`)"
      - "traefik.http.services.smartmetserver.loadbalancer.server.port=8080"
    volumes:
      - /smartmet/data/gfs/eastafrica/surface/querydata:/smartmet/data/gfs/surface
      - /smartmet/data/gfs/eastafrica/pressure/querydata:/smartmet/data/gfs/pressure
      - /smartmet/data/ecmwf/world/surface/querydata:/smartmet/data/ecmwf/surface
      - smartmetserver-storage-cnf:/etc/smartmet
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "2"
    networks:
      - traefik-network
    restart: unless-stopped
  ecmwf-surface:
    image: fmidev/fmidownloader
    container_name: fmidownloader-ecmwf-surface
    command:
      - "--producer=ecmwf"
      - "--dir=surface"
      - "--filename=ecmwf_world_surface"
      - "--parameters=Temperature,DewPoint,Humidity,WindDirection,WindSpeedMS,WindGust,TotalCloudCover,Precipitation1h,WeatherSymbol3,Pressure,CAPE,CIN"
    volumes:
      - model-fmi-ecmwf:/tmp
    restart: unless-stopped
volumes:
  smartmetserver-storage-cnf:
  model-fmi-ecmwf:
    name: model-fmi-ecmwf
    
networks:
    traefik-network:
      external: true
